name: arduino-lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: arduino/arduino-lint-action@v1
        with:
          # path: ./
          version: 1.x
          compliance: strict
          library-manager: submit
          project-type: library
          recursive: false
          # report-file:
          verbose: false
          token: GITHUB_TOKEN